site_name: MCP Docs
site_url: https://limegradient.github.io/RetroMCP-Docs/
nav:
  - Home: index.md
  - About: about.md
  - MCP: mcp.md
  - Beta:
    - RetroMCP (No ModLoader):
      - Getting Started: beta/mcp/gettingstarted.md
      - Making a Block: beta/mcp/block.md
      - Making a Item: beta/mcp/item.md
      - Making a Recipe: beta/mcp/recipe.md
  - Legacy Console Edition:
    - Editing PCK Files: lce/pckediting.md
theme:
  name: dracula