site_name: MCP Docs
site_url: https://limegradient.github.io/RetroMCP-Docs/
nav:
  - Home: index.md
  - About: about.md
  - MCP: mcp.md
  - Beta:
    - Getting Started: beta/gettingstarted.md
    - RetroMCP (No ModLoader):
      - Making a Block: beta/mcp/block.md
      - Making a Item: beta/mcp/item.md
      - Making a Recipe: beta/mcp/recipe.md
  - Legacy Console Edition:
    - Modding:
      - Getting Started: lce/modding/gettingstarted.md
      - Editing PCK Files: lce/modding/pckediting.md
    - Game Resources: lce/resourcepacks.md
theme:
  name: dracula